codecov:
  notify:
    require_ci_to_pass: yes
  status:
    project:
      default:
        # Allow small drops in coverage
        threshold: 0.005  # .5 %
        if_not_found: failure

coverage:
  precision: 2
  round: down
  range: "70...100"

parsers:
  javascript:
    enable_partials: yes

ignore:
  - "BookReader"
  - "tests"

